Repository eslint/playground, pull requests merged in 2022-07, with the labels that each got.

#84 fix: donate link
  src/_includes/components/navigation.html
Labels: bug, triage

#85 fix: enhance 404 page UI
  src/assets/scss/foundations.scss
  src/assets/scss/layout.scss
  src/pages/404.html
Labels: bug, triage

#86 chore: preselect default theme
  src/assets/js/themes.js
Labels: chore, accepted

#90 fix: clean ruleName
  src/playground/utils/codemirror-linter-extension.js
Labels: bug, accepted

#87 fix: migrate configuration code from js file to react
  src/assets/js/main.js
  src/playground/App.js
Labels: bug, accepted

#91 fix: show toggle theme toggle btn in safari
  src/_includes/layouts/base.html
  src/assets/js/themes.js
  src/assets/scss/components/social-icons.scss
  src/playground/components/ThemeSwitcher.js
Labels: bug, accepted

#92 chore: remove unwanted conditionals
  src/playground/components/RuleItem.js
  src/playground/components/ThemeSwitcher.js
Labels: triage, chore
