Repository eslint/playground, pull requests merged in 2022-05, with the labels that each got.

#45 fix: fix broken link
  src/playground/components/Footer.js
Labels: bug, triage

#48 fix: fix mobile layout issue
  src/assets/scss/foundations.scss
  src/assets/scss/layout.scss
Labels: bug, triage

#47 perf: use react v18
  package-lock.json
  package.json
  src/playground/index.js
Labels: triage, chore

#52 fix: migrate from `node-sass` to `dart-sass`
  package-lock.json
  package.json
  src/assets/scss/tokens/themes.scss
Labels: bug, triage

#53 chore: remove dart-sass
  package-lock.json
  package.json
Labels: triage, chore

#49 fix: update react-select to v5.3.2
  package-lock.json
  package.json
Labels: bug, triage

#51 fix: show error on invalid JSON in rule config
  src/assets/scss/components/playground-configuration.scss
  src/playground/components/Configuration.js
Labels: bug, triage

#54 feat: add react hooks plugin
  .eslintrc.js
  package-lock.json
  package.json
Labels: chore

#56 chore: add check before accessing elements
  src/assets/js/main.js
  src/assets/js/themes.js
Labels: triage, chore

#58 fix: selected rule not clearing issue
  src/playground/components/Configuration.js
Labels: bug

#61 fix: fix typos
  src/_data/languages.json
  src/assets/js/focus-visible.js
Labels: bug, triage
