Repository eslint/playground, pull requests merged in 2022-06, with the labels that each got.

#63 fix: remove colon if no line number in error
  src/playground/components/Alert.js
Labels: bug, triage

#60 fix: fix donate link
  src/_data/navigation.json
  src/_includes/components/navigation.html
Labels: bug, triage

#59 feat: add resize option
  package-lock.json
  package.json
  src/assets/scss/layout.scss
  src/playground/App.js
  src/playground/scss/split-pane.scss
Labels: triage, feature

#65 fix: font ligatures
  src/playground/utils/codemirror-theme.js
Labels: bug, triage

#66 fix: autocomplete tooltip ui not visible in light mode
  src/playground/utils/codemirror-theme.js
Labels: bug, triage

#70 fix: avoid theme flash
  src/_includes/layouts/base.njk
  src/assets/js/themes.js
Labels: bug, triage

#68 chore: show progress while bundling via webpack
  package.json
Labels: triage, chore

#71 chore: update package.json
  package.json
Labels: triage, chore

#72 chore: remove redundant props
  src/playground/App.js
Labels: triage, chore

#67 fix: show error on invalid rule config
  package-lock.json
  src/assets/scss/components/playground-configuration.scss
  src/playground/App.js
  src/playground/components/Configuration.js
  src/playground/package.json
Labels: bug

#76 ci: update github actions
  .github/workflows/ci.yml
Labels: triage, build

#73 chore: Sync with other sites
  .eleventy.js
  package-lock.json
  package.json
  src/_data/links.json
  src/_data/navigation.json
  src/_data/site.js
  src/_data/sites/en.yml
  src/_includes/components/navigation.html
  src/_includes/layouts/base.html
  src/_includes/layouts/main.html
  src/_includes/partials/analytics.html
  src/_includes/partials/header.html
  src/playground/package.json
Labels: triage, chore

#77 fix: Use replaceState on code changes
  src/playground/App.js
Labels: bug, triage

#80 chore: update eslint url in readme
  README.md
Labels: triage, chore

#62 chore: update build command
  package.json
  tools/dev-server.js
Labels: triage, chore

#78 chore: remove unwanted react fragments and added lint rule
  .eslintrc.js
  src/playground/components/CodeEditor.js
  src/playground/components/CrashAlert.js
Labels: triage, chore

#64 fix: show navlist when script disabled
  src/_includes/components/navigation.html
  src/_includes/layouts/base.html
  src/assets/scss/components/navigation.scss
Labels: bug, triage
